version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID} 